PanelLock()
PanelUpdateEnable(0)

	HostFieldPutData("#2K2NB",0,"  ")
	from139 = ""

HostScreenSendKey("F9")
HostWaitII(10)

If ScreenIdGet() = "(77)" Then 
	Goto End_script
EndIf 
If ScreenIdGet() = "(151)" Then 
	If Trim(@"@(MESSAGE)@") <> "" Then 
		MessageBox("Message",@"@(MESSAGE)@",4,0)
	EndIf 
	HostScreenSendKey("F15")
	HostWaitII(10)
EndIf 
End_script: 
PanelUnlock()
'PanelUpdateEnable(7)
End 