PanelLock()
PanelUpdateEnable(0)

If ScreenIdGet() = "(178)" Then 
	HostScreenSendKey("F12")
	HostWaitII(10)
	HostScreenSendKey("F12")
	HostWaitII(10)
EndIf 

HostScreenSendKey("F3")
HostWaitII(10)
If ScreenIdGet() <> "SIGNON" Then 
	HostScreenSendKey("F3")
	HostWaitII(10)
EndIf 
If ScreenIdGet() <> "SIGNON" Then 
HostScreenPutString("90")
	HostScreenSendKey("ENTER")
	HostWaitII(10)
EndIf 
PanelUnLock()
PanelUpdateEnable(7)
